// Code generated by protoc-gen-go-kit-grpc. DO NOT EDIT.

package test

import (
	grpc "google.golang.org/grpc"
	insecure "google.golang.org/grpc/credentials/insecure"
	os "os"
)

func GetNewWalletClient() WalletClient {
	var host string
	if os.Getenv("CONTAINER") != "" {
		host = "Wallet"

	} else {
		host = "localhost"
	}
	dial, err := grpc.Dial(host+":8080", grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		panic(err)
	}

	return NewWalletClient(dial)
}
