// Code generated by protoc-gen-go-kit-grpc.

package test

import (
	"context"

	pb "test/proto"
)

type WalletHandler struct {
	pb.UnimplementedWalletServer
}

// insert 234124321
// adasda
// frtgrt
// asdad
func (e *WalletHandler) Insert(ctx context.Context, req *pb.DeleteRequest) (*pb.InsertResponse, error) {
	//TODO:implement
	return nil, nil
}
func (e *WalletHandler) Delete(ctx context.Context, req *pb.DeleteRequest) (*pb.DeleteResponse, error) {
	//TODO:implement
	return nil, nil
}
func (e *WalletHandler) ClientStream(stream pb.Wallet_ClientStreamServer) error {
	//TODO:implement
	return nil
}
func (e *WalletHandler) ServerStream(req *pb.ServerStreamRequest, stream pb.Wallet_ServerStreamServer) error {
	//TODO:implement
	return nil
}
func (e *WalletHandler) BidiStream(stream pb.Wallet_BidiStreamServer) error {
	//TODO:implement
	return nil
}
